server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aymanecoder/microservice-config-server
          clone-on-start: true

