server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0

#okta config api-gateway
okta:
  oauth2:
    issuer: https://dev-36008585.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaaownk96zgNO5tq5d7
    client-secret: Vogqfvd_N-lNNhEjl9IDFUy7rG7G0ca1NPhQMd3P877pQ7QjLfLUHzdYHo4KuvlI
    scopes:  openid, profile, email, offline_access