server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: aymane
      password: root
      database: microservices

  application:
    name: RATING-SERVICE

  config:
    import: optional:configserver:http://localhost:8085
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0

okta:
  oauth2:
    issuer: https://dev-36008585.okta.com/oauth2/default
    audience: api/default