server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: aymane
      password: root
      database: microservices

  application:
    name: RATING-SERVICE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
